name: Reusable WF - Build

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      amalgam-version: ${{ steps.get-amalgam-version.outputs.amalgam-version }}
    steps:
    - uses: actions/checkout@v3

    - name: Get Amalgam dependency version
      id: get-amalgam-version
      run: |
        AMALGAM_VERSION=$(jq -r ".dependencies.amalgam" ./version.json)
        echo "amalgam-version=$(echo $AMALGAM_VERSION)" >> $GITHUB_OUTPUT

    - name: Download Amalgam
      uses: robinraju/release-downloader@v1.8
      with:
        repository: "howsoai/amalgam"
        tag: ${{ steps.get-amalgam-version.outputs.amalgam-version }}
        fileName: "*linux-amd64*"
        out-file-path: "target"
        extract: true

    - name: Build
      run: |
        ./build.sh build_package ${{ inputs.version }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: howso-engine-${{ inputs.version }}
        path: target/howso-engine-${{ inputs.version }}.tar.gz
        if-no-files-found: error

  test-linux-amd64:
    needs: ['build']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Download Amalgam
      uses: robinraju/release-downloader@v1.8
      with:
        repository: "howsoai/amalgam"
        tag: ${{ needs.build.outputs.amalgam-version }}
        fileName: "*linux-amd64*"
        out-file-path: "target"
        extract: true

    - name: Amalgam version
      run: |
        ${{ github.workspace }}/target/bin/amalgam-mt --version

    - name: Test
      run: |
        sudo locale-gen es_ES.utf8
        ./build.sh test ${{ inputs.version }}

  test-macos-amd64:
    needs: ['build']
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Download Amalgam
      uses: robinraju/release-downloader@v1.8
      with:
        repository: "howsoai/amalgam"
        tag: ${{ needs.build.outputs.amalgam-version }}
        fileName: "*darwin-amd64*"
        out-file-path: "target"
        extract: true

    # GitHub macos runner does not support AVX
    - name: Amalgam version
      run: |
        ${{ github.workspace }}/target/bin/amalgam-mt-noavx --version

    - name: Test
      run: |
        ./build.sh test ${{ inputs.version }}

  test-windows-amd64:
    needs: ['build']
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Download Amalgam
      uses: robinraju/release-downloader@v1.8
      with:
        repository: "howsoai/amalgam"
        tag: ${{ needs.build.outputs.amalgam-version }}
        fileName: "*windows-amd64*"
        out-file-path: "target"
        extract: true

    - name: Download tz data
      shell: pwsh
      run: |
        ./build/powershell/Download-Tzdata.ps1

    - name: Amalgam version
      run: |
        "${{ github.workspace }}/target/bin/amalgam-mt.exe" --version

    - name: Test
      run: |
        ./build.sh test ${{ inputs.version }}
